name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
 
    - name: Run Cypress tests
      uses: cypress-io/github-action@v6
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: success() || failure()
      with:
        report_paths: '**/results/output.xml'
        token: ${{secrets.GITHUB_TOKEN}}

